sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-1-658939246822"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id:
#     secure: "$AWS_ACCESS_KEY"
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAZS26W7DTCZJL2Q6Q"
  secret_access_key:
    secure: "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"
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-658939246822"